### ISSUE TITLE
Gandyn does not work anymore

### ISSUE THREAD

**Issue by ignace72** [Danamir/dyn-gandi#2]
Hello
Gandyn does not work anymore, this is the exit of the terminal.
If someone has an idea ?
Thank you

`Traceback (most recent call last):
  File "/home/ignace/Téléchargements/gandyn/gandyn-master/src/dyn-gandi-master/.env/bin/dyn_gandi", line 11, in <module>
    load_entry_point('dyn-gandi==1.0', 'console_scripts', 'dyn_gandi')()
  File "/home/ignace/Téléchargements/gandyn/gandyn-master/src/dyn-gandi-master/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ignace/Téléchargements/gandyn/gandyn-master/src/dyn-gandi-master/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/ignace/Téléchargements/gandyn/gandyn-master/src/dyn-gandi-master/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/ignace/Téléchargements/gandyn/gandyn-master/src/dyn-gandi-master/.env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'dyn_gandi'`

**Comment by Danamir** [comment]
Hello,

The script is still working on my machine, but I have not tried it with Python 3.7.

Did you try to do a `pyclean` and `python setup.py develop` again ? Or to launch `python dyn_gandi.py` instead of `dyn_gandi` entry point ?

_Edit_: Tested on a fresh Python 3.7 virtual env, without problem.

**Comment by ignace72** [comment]
Hello,
I do not have the pyclean command.
I have a new problem:
python setup.py gives me:
(I use python 3.7)

`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied`

**Comment by Danamir** [comment]
You have to type the full command `python setup.py develop`.

**Comment by ignace72** [comment]
I have the following error:

2018-08-30 20:42:13 - LiveDNS error: The ignace72.eu domain does not exist. [ERROR]
2018-08-30 20:42:13 - LiveDNS error: The ignace72.eu domain does not exist. [ERROR]

I tried with https:// but it's not better.
Thank you

**Comment by Danamir** [comment]
This is a problem reported from LiveDNS, are you sure your configuration is correct ? (key and domain in particular)

**Comment by ignace72** [comment]
Hello.
I changed my API key and now it works.
Thank you very much for your help.

**Comment by Danamir** [comment]
No problem.
